package dropp

import ()

// EbayPrice contains the price and currency as fetched from the Ebay service
type EbayPrice struct {
	CurrencyID string `json:"_currencyID"`
	Value      string `json:"value"`
}

// EbayItem is the full item generated by the Ebay service
type EbayItem struct {
	CurrentPrice EbayPrice `json:"current_price"`
	ID           string    `json:"id"`
	ItemName     string    `json:"name"`
	StockCount   string    `json:"quantity"`
	SoldCount    string    `json:"quantity_sold"`
	Status       string    `json:"status"`
	ItemPageURL  string    `json:"url"`
}

// EbayStatus manages the communication with the ebay service
type EbayStatus int

const (
	// OnEbay means the item is available for purchase on Ebay
	OnEbay EbayStatus = iota

	// OffEbay means the item is not available for purchase on Ebay
	OffEbay

	// UnkEbay means the items status could not be retrieved
	UnkEbay
)
