---
apiVersion: v1
kind: Pod
metadata:
  name: ebay-service
  labels:
    app: dropp

spec:
  containers:
  - name: ebay-service
    image: us.gcr.io/dropp-prod/ebay-service
    imagePullPolicy: Always
